-- GEAR catalog, administered through Supabase Studio during the first stage.
-- Run once in the Supabase SQL Editor. No account or personal data is seeded.
create table if not exists public.catalog_entries (
  id integer generated by default as identity (start with 1000) primary key,
  name text not null check (length(trim(name)) > 0),
  kind text not null default 'Автосервис',
  category text not null check (length(trim(category)) > 0),
  service text not null check (length(trim(service)) > 0),
  description text,
  city text not null check (length(trim(city)) > 0),
  address text not null check (length(trim(address)) > 0),
  lat double precision not null check (lat between -90 and 90),
  lng double precision not null check (lng between -180 and 180),
  locations jsonb not null default '[]'::jsonb check (jsonb_typeof(locations) = 'array'),
  offerings jsonb not null default '[]'::jsonb check (jsonb_typeof(offerings) = 'array'),
  brands text[] not null default array['Все марки']::text[],
  supported_models jsonb not null default '{}'::jsonb check (jsonb_typeof(supported_models) = 'object'),
  price_byn integer not null check (price_byn >= 0),
  price_label text not null check (length(trim(price_label)) > 0),
  payment_methods text[] not null default array['cash']::text[],
  phone text not null default '',
  open_now boolean not null default false,
  available_today boolean not null default false,
  around_clock boolean not null default false,
  mobile boolean not null default false,
  urgent boolean not null default false,
  promoted boolean not null default false,
  is_demo boolean not null default false,
  status text not null default 'draft' check (status in ('draft','published','hidden')),
  constraint published_listing_has_contact check (status <> 'published' or is_demo or length(trim(phone)) > 0),
  created_at timestamptz not null default now(),
  published_at timestamptz
);

create index if not exists catalog_entries_published_idx
  on public.catalog_entries (published_at desc, id desc)
  where status = 'published';

alter table public.catalog_entries enable row level security;
revoke all on public.catalog_entries from anon, authenticated;
grant select on public.catalog_entries to anon, authenticated;

drop policy if exists catalog_entries_public_read on public.catalog_entries;
create policy catalog_entries_public_read on public.catalog_entries
  for select to anon, authenticated using (status = 'published');

-- There are deliberately no INSERT/UPDATE/DELETE policies for public roles.
-- Drafts can be edited and published by the project owner in Supabase Studio.

insert into public.catalog_entries
  (id, name, kind, category, service, description, city, address, lat, lng,
   brands, price_byn, price_label, payment_methods, is_demo, status)
values
  (1000, 'GEAR Демо БД', 'Автосервис', 'Диагностика', 'Диагностика автомобиля (пример)',
   'Тестовая карточка из базы данных. Услуга и расположение приведены только для проверки каталога.',
   'Минск', 'Минск, демонстрационная точка', 53.9006, 27.5590,
   array['Все марки'], 35, 'от 35 BYN', array['cash'], true, 'published')
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.catalog_entries','id'),
  greatest((select max(id) from public.catalog_entries), 1000), true);
